### ISSUE TITLE
the repository for this project is empty

### ISSUE THREAD

**Issue by faouziabenabbou** [NorhanKhaled/SkillsAcademy-CAD#43]
Hi,
thanks to take look to my issue.
My app is running :
![image](https://user-images.githubusercontent.com/64813598/81217986-fda87f00-8fcc-11ea-84d2-42c2b75e27d0.png)
but when i go to GIT, it say that my project is empty how to fix it?
![image](https://user-images.githubusercontent.com/64813598/81218179-55df8100-8fcd-11ea-8f3e-99409fc4892b.png)

thanks

**Comment by NorhanKhaled** [comment]
did you push your application on gitlab ? 
I think you deployed your application on the cloud foundry if you were making ex01 , in the next exercises you will learn how to add code to gitlab :)

**Comment by faouziabenabbou** [comment]
yes, I deployed my application on the cloud foundry

**Comment by faouziabenabbou** [comment]
I am in exercice 2/ Developing IBM Cloud applications with IBM Cloud Continuous Delivery

**Comment by NorhanKhaled** [comment]
I did the exercise steps now , I think you missed a step or try to refresh the gitlab screen 
It should be like this 
![image](https://user-images.githubusercontent.com/21022185/81219908-2a6a8f80-8fe9-11ea-8ea5-4de5e7d7de92.png)

**Comment by faouziabenabbou** [comment]
i have the same problem, i tried to push my foder to git , this is the result 
![image](https://user-images.githubusercontent.com/64813598/81238958-f5633a80-8ff2-11ea-90c5-7be485af0adb.png)

**Comment by faouziabenabbou** [comment]
I'm sorry but i am blocked for this issue if you can help me :

![image](https://user-images.githubusercontent.com/64813598/81243092-60663e80-8ffe-11ea-88fb-684aa1cf03e2.png)
